"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Registers = void 0;
var Registers;
(function (Registers) {
    // Registers
    Registers[Registers["REG_bXCR"] = 128] = "REG_bXCR";
    Registers[Registers["REG_bXSR"] = 129] = "REG_bXSR";
    Registers[Registers["REG_bSDC1"] = 130] = "REG_bSDC1";
    Registers[Registers["REG_bCM1"] = 131] = "REG_bCM1";
    Registers[Registers["REG_bNC"] = 132] = "REG_bNC";
    Registers[Registers["REG_bMSGC"] = 133] = "REG_bMSGC";
    Registers[Registers["REG_bMSGS"] = 134] = "REG_bMSGS";
    Registers[Registers["REG_bNPR"] = 135] = "REG_bNPR";
    Registers[Registers["REG_bIE"] = 136] = "REG_bIE";
    Registers[Registers["REG_bGA"] = 137] = "REG_bGA";
    Registers[Registers["REG_bNAH"] = 138] = "REG_bNAH";
    Registers[Registers["REG_bNAL"] = 139] = "REG_bNAL";
    Registers[Registers["REG_bSDC2"] = 140] = "REG_bSDC2";
    Registers[Registers["REG_bSDC3"] = 141] = "REG_bSDC3";
    Registers[Registers["REG_bCM2"] = 142] = "REG_bCM2";
    Registers[Registers["REG_bNDR"] = 143] = "REG_bNDR";
    Registers[Registers["REG_bMPR"] = 144] = "REG_bMPR";
    Registers[Registers["REG_bMDR"] = 145] = "REG_bMDR";
    Registers[Registers["REG_bCM3"] = 146] = "REG_bCM3";
    Registers[Registers["REG_bCM4"] = 147] = "REG_bCM4";
    Registers[Registers["REG_bFRHL"] = 148] = "REG_bFRHL";
    Registers[Registers["REG_bFRLO"] = 149] = "REG_bFRLO";
    Registers[Registers["REG_bSBC"] = 150] = "REG_bSBC";
    Registers[Registers["REG_bXSR2"] = 151] = "REG_bXSR2";
    Registers[Registers["REG_mRCMB"] = 160] = "REG_mRCMB";
    Registers[Registers["REG_bXTIM"] = 190] = "REG_bXTIM";
    Registers[Registers["REG_bXRTY"] = 191] = "REG_bXRTY";
    Registers[Registers["REG_mXCMB"] = 192] = "REG_mXCMB";
    Registers[Registers["REG_bXTS"] = 213] = "REG_bXTS";
    Registers[Registers["REG_bPCTC"] = 226] = "REG_bPCTC";
    Registers[Registers["REG_bPCTS"] = 227] = "REG_bPCTS";
    Registers[Registers["REG_bAPAH"] = 232] = "REG_bAPAH";
    Registers[Registers["REG_bAPAL"] = 233] = "REG_bAPAL";
    Registers[Registers["REG_bPSTX"] = 234] = "REG_bPSTX";
    Registers[Registers["REG_bPLDT"] = 236] = "REG_bPLDT";
    Registers[Registers["REG_bPPI"] = 242] = "REG_bPPI";
    Registers[Registers["REG_mARP"] = 384] = "REG_mARP";
    Registers[Registers["REG_mAXP"] = 448] = "REG_mAXP";
    Registers[Registers["REG_bXLRTY"] = 960] = "REG_bXLRTY";
    Registers[Registers["REG_bXSTIM"] = 961] = "REG_bXSTIM";
    // Register bXCR Transceiver Control Register 0x80
    Registers[Registers["bXCR_MASTER"] = 128] = "bXCR_MASTER";
    Registers[Registers["bXCR_SLAVE"] = 0] = "bXCR_SLAVE";
    Registers[Registers["bXCR_OUTPUT_ENABLE"] = 64] = "bXCR_OUTPUT_ENABLE";
    Registers[Registers["bXCR_OUTPUT_DISABLE"] = 0] = "bXCR_OUTPUT_DISABLE";
    Registers[Registers["bXCR_LEGACY_BYPASS"] = 32] = "bXCR_LEGACY_BYPASS";
    Registers[Registers["bXCR_ENHANCED_BYPASS"] = 0] = "bXCR_ENHANCED_BYPASS";
    Registers[Registers["bXCR_LOWPOWER_WAKE_EN"] = 0] = "bXCR_LOWPOWER_WAKE_EN";
    Registers[Registers["bXCR_LOWPOWER_WAKE_DIS"] = 16] = "bXCR_LOWPOWER_WAKE_DIS";
    Registers[Registers["bXCR_STANDALONE_EN"] = 8] = "bXCR_STANDALONE_EN";
    Registers[Registers["bXCR_STANDALONE_DIS"] = 0] = "bXCR_STANDALONE_DIS";
    Registers[Registers["bXCR_SOURCE_BYPASS_DIS"] = 0] = "bXCR_SOURCE_BYPASS_DIS";
    Registers[Registers["bXCR_SOURCE_BYPASS_EN"] = 4] = "bXCR_SOURCE_BYPASS_EN";
    Registers[Registers["bXCR_ALL_BYPASS_EN"] = 0] = "bXCR_ALL_BYPASS_EN";
    Registers[Registers["bXCR_ALL_BYPASS_DIS"] = 2] = "bXCR_ALL_BYPASS_DIS";
    Registers[Registers["bXCR_REN_EN"] = 0] = "bXCR_REN_EN";
    Registers[Registers["bXCR_REN_DIS"] = 1] = "bXCR_REN_DIS";
    // Register bXSR Transceiver Status Register 0x81
    Registers[Registers["bXSR_FREQ_REG_ACT"] = 128] = "bXSR_FREQ_REG_ACT";
    Registers[Registers["bXSR_FREQ_REG_INACT"] = 0] = "bXSR_FREQ_REG_INACT";
    Registers[Registers["bXSR_SPDIF_ERR_MASK"] = 64] = "bXSR_SPDIF_ERR_MASK";
    Registers[Registers["bXSR_SPDIF_ERR_EN"] = 0] = "bXSR_SPDIF_ERR_EN";
    Registers[Registers["bXSR_LOCK_ERR_MASK"] = 32] = "bXSR_LOCK_ERR_MASK";
    Registers[Registers["bXSR_LOCK_ERR_EN"] = 0] = "bXSR_LOCK_ERR_EN";
    Registers[Registers["bXSR_CODING_ERR_MASK"] = 16] = "bXSR_CODING_ERR_MASK";
    Registers[Registers["bXSR_CODING_ERR_EN"] = 0] = "bXSR_CODING_ERR_EN";
    Registers[Registers["bXSR_ERR_ACT"] = 8] = "bXSR_ERR_ACT";
    Registers[Registers["bXSR_ERR_CLR"] = 0] = "bXSR_ERR_CLR";
    Registers[Registers["bXSR_FREQ_REG_LOCKED"] = 4] = "bXSR_FREQ_REG_LOCKED";
    Registers[Registers["bXSR_FREQ_REG_UNLOCKED"] = 0] = "bXSR_FREQ_REG_UNLOCKED";
    Registers[Registers["bXSR_SPDIF_LOCK_ACT"] = 2] = "bXSR_SPDIF_LOCK_ACT";
    Registers[Registers["bXSR_SPDIF_LOCK_INACT"] = 0] = "bXSR_SPDIF_LOCK_INACT";
    Registers[Registers["bXSR_TRANS_LOCK_ACT"] = 1] = "bXSR_TRANS_LOCK_ACT";
    Registers[Registers["bXSR_TRANS_LOCK_INACT"] = 0] = "bXSR_TRANS_LOCK_INACT";
    // Register bSDC1 Source Data Control Register 0x82
    Registers[Registers["bSDC1_ACTIVE_EDGE_EN"] = 128] = "bSDC1_ACTIVE_EDGE_EN";
    Registers[Registers["bSDC1_ACTIVE_EDGE_DIS"] = 0] = "bSDC1_ACTIVE_EDGE_DIS";
    Registers[Registers["bSDC1_DELAY_FIRST_BIT_EN"] = 64] = "bSDC1_DELAY_FIRST_BIT_EN";
    Registers[Registers["bSDC1_DELAY_FIRST_BIT_DIS"] = 0] = "bSDC1_DELAY_FIRST_BIT_DIS";
    Registers[Registers["bSDC1_POLARITY_FSY_RISING"] = 32] = "bSDC1_POLARITY_FSY_RISING";
    Registers[Registers["bSDC1_POLARITY_FSY_FALLING"] = 0] = "bSDC1_POLARITY_FSY_FALLING";
    Registers[Registers["bSDC1_SCK_OUTPUT"] = 16] = "bSDC1_SCK_OUTPUT";
    Registers[Registers["bSDC1_SCK_INPUT"] = 0] = "bSDC1_SCK_INPUT";
    Registers[Registers["bSDC1_NO_CYCLES_DEF"] = 0] = "bSDC1_NO_CYCLES_DEF";
    Registers[Registers["bSDC1_NO_CYCLES_DIV"] = 8] = "bSDC1_NO_CYCLES_DIV";
    Registers[Registers["bSDC1_SPDIF_EN"] = 4] = "bSDC1_SPDIF_EN";
    Registers[Registers["bSDC1_SPDIF_DIS"] = 0] = "bSDC1_SPDIF_DIS";
    Registers[Registers["bSDC1_MUTE_SOURCE"] = 0] = "bSDC1_MUTE_SOURCE";
    Registers[Registers["bSDC1_UNMUTE_SOURCE"] = 2] = "bSDC1_UNMUTE_SOURCE";
    Registers[Registers["bSDC1_TRANSPARENT_EN"] = 0] = "bSDC1_TRANSPARENT_EN";
    Registers[Registers["bSDC1_TRANSPARENT_DIS"] = 1] = "bSDC1_TRANSPARENT_DIS";
    // Register bCM1 Clock Manager 1 0x83
    Registers[Registers["bCM1_PLL_DISABLE"] = 128] = "bCM1_PLL_DISABLE";
    Registers[Registers["bCM1_PLL_ENABLE"] = 0] = "bCM1_PLL_ENABLE";
    Registers[Registers["bCM1_RMCK_DIV_384F"] = 0] = "bCM1_RMCK_DIV_384F";
    Registers[Registers["bCM1_RMCK_DIV_256F"] = 16] = "bCM1_RMCK_DIV_256F";
    Registers[Registers["bCM1_RMCK_DIV_128F"] = 32] = "bCM1_RMCK_DIV_128F";
    Registers[Registers["bCM1_RMCK_DIV_64F"] = 48] = "bCM1_RMCK_DIV_64F";
    Registers[Registers["bCM1_RMCK_DIV_1536F"] = 64] = "bCM1_RMCK_DIV_1536F";
    Registers[Registers["bCM1_RMCK_DIV_1024F"] = 80] = "bCM1_RMCK_DIV_1024F";
    Registers[Registers["bCM1_RMCK_DIV_768F"] = 96] = "bCM1_RMCK_DIV_768F";
    Registers[Registers["bCM1_RMCK_DIV_512F"] = 112] = "bCM1_RMCK_DIV_512F";
    Registers[Registers["bCM1_CRYSTAL_DIVIDER_256F"] = 0] = "bCM1_CRYSTAL_DIVIDER_256F";
    Registers[Registers["bCM1_CRYSTAL_DIVIDER_384F"] = 4] = "bCM1_CRYSTAL_DIVIDER_384F";
    Registers[Registers["bCM1_PLL_INPUT_MOST"] = 0] = "bCM1_PLL_INPUT_MOST";
    Registers[Registers["bCM1_PLL_INPUT_SR0"] = 1] = "bCM1_PLL_INPUT_SR0";
    Registers[Registers["bCM1_PLL_INPUT_CRYSTAL"] = 2] = "bCM1_PLL_INPUT_CRYSTAL";
    Registers[Registers["bCM1_PLL_INPUT_SCK"] = 3] = "bCM1_PLL_INPUT_SCK";
    // Register bMSGC Message Control Register 0x85
    Registers[Registers["bMSGC_START_TX"] = 128] = "bMSGC_START_TX";
    Registers[Registers["bMSGC_STOP_TX"] = 0] = "bMSGC_STOP_TX";
    Registers[Registers["bMSGC_RECEIVE_BUFF_EN"] = 64] = "bMSGC_RECEIVE_BUFF_EN";
    Registers[Registers["bMSGC_RECEIVE_BUFF_DIS"] = 0] = "bMSGC_RECEIVE_BUFF_DIS";
    Registers[Registers["bMSGC_RESERVED"] = 0] = "bMSGC_RESERVED";
    Registers[Registers["bMSGC_START_ADDRESS_INIT_EN"] = 16] = "bMSGC_START_ADDRESS_INIT_EN";
    Registers[Registers["bMSGC_START_ADDRESS_INIT_DIS"] = 0] = "bMSGC_START_ADDRESS_INIT_DIS";
    Registers[Registers["bMSGC_RESET_NET_CONF_CHANGE"] = 8] = "bMSGC_RESET_NET_CONF_CHANGE";
    Registers[Registers["bMSGC_RESET_ERR_INT"] = 4] = "bMSGC_RESET_ERR_INT";
    Registers[Registers["bMSGC_RESET_MESSAGE_TX_INT"] = 2] = "bMSGC_RESET_MESSAGE_TX_INT";
    Registers[Registers["bMSGC_RESET_MESSAGE_RX_INT"] = 1] = "bMSGC_RESET_MESSAGE_RX_INT";
    // Register bMSGS Message Status Register 0x86
    Registers[Registers["bMSGS_RECEIVE_BUFF_STATUS_READY"] = 0] = "bMSGS_RECEIVE_BUFF_STATUS_READY";
    Registers[Registers["bMSGS_RECEIVE_BUFF_STATUS_FULL"] = 128] = "bMSGS_RECEIVE_BUFF_STATUS_FULL";
    Registers[Registers["bMSGS_TRANS_SUCCESS"] = 64] = "bMSGS_TRANS_SUCCESS";
    Registers[Registers["bMSGS_NET_CHANGED"] = 8] = "bMSGS_NET_CHANGED";
    Registers[Registers["bMSGS_ERR"] = 4] = "bMSGS_ERR";
    Registers[Registers["bMSGS_MESS_TRANSMITTED"] = 2] = "bMSGS_MESS_TRANSMITTED";
    Registers[Registers["bMSGS_MESS_RECEIVED"] = 1] = "bMSGS_MESS_RECEIVED";
    // Register bIE Interrupt Enable Register
    Registers[Registers["bIE_NET_CHANGED_INT_EN"] = 8] = "bIE_NET_CHANGED_INT_EN";
    Registers[Registers["bIE_ERR_INT_EN"] = 4] = "bIE_ERR_INT_EN";
    Registers[Registers["bIE_TX_INT_EN"] = 2] = "bIE_TX_INT_EN";
    Registers[Registers["bIE_RX_INT_EN"] = 1] = "bIE_RX_INT_EN";
    // Register source control 2
    Registers[Registers["bSDC2_SCK_8F"] = 0] = "bSDC2_SCK_8F";
    Registers[Registers["bSDC2_SCK_16F"] = 32] = "bSDC2_SCK_16F";
    Registers[Registers["bSDC2_SCK_32F"] = 64] = "bSDC2_SCK_32F";
    Registers[Registers["bSDC2_SCK_64F"] = 96] = "bSDC2_SCK_64F";
    Registers[Registers["bSDC2_SCK_128F"] = 128] = "bSDC2_SCK_128F";
    Registers[Registers["bSDC2_SCK_256F"] = 160] = "bSDC2_SCK_256F";
    // Clock Manager 2
    Registers[Registers["bCM2_UNLOCKED"] = 128] = "bCM2_UNLOCKED";
    Registers[Registers["BCM2_NETWORK_ACTIVITY"] = 64] = "BCM2_NETWORK_ACTIVITY";
    /// //Legacy testing/////
    // bSDC3
    Registers[Registers["bSDC3_MUTE_SOURCE_PORTS"] = 2] = "bSDC3_MUTE_SOURCE_PORTS";
    Registers[Registers["bSDC3_UNMUTE_SOURCE_PORTS"] = 0] = "bSDC3_UNMUTE_SOURCE_PORTS";
    Registers[Registers["bSDC3_SOURCE_PORT_EN"] = 0] = "bSDC3_SOURCE_PORT_EN";
    Registers[Registers["bSDC3_SOURCE_PORT_DIS"] = 1] = "bSDC3_SOURCE_PORT_DIS";
    // bCM3
    Registers[Registers["bCM3_FREN_EN"] = 16] = "bCM3_FREN_EN";
    Registers[Registers["bCM3_FREN_DIS"] = 0] = "bCM3_FREN_DIS";
    Registers[Registers["bCM3_ENH"] = 64] = "bCM3_ENH";
    Registers[Registers["bCM3_AUTO_SWITCH_CLOCK"] = 8] = "bCM3_AUTO_SWITCH_CLOCK";
    Registers[Registers["bCM3_DIS_AUTO_SWITCH_CLOCK"] = 0] = "bCM3_DIS_AUTO_SWITCH_CLOCK";
    Registers[Registers["bCM3_AUTO_CRYSTAL_EN"] = 4] = "bCM3_AUTO_CRYSTAL_EN";
    Registers[Registers["bCM3_AUTO_CRYSTAL_DIS"] = 0] = "bCM3_AUTO_CRYSTAL_DIS";
    Registers[Registers["bCM3_FREQ_REG_RESET"] = 2] = "bCM3_FREQ_REG_RESET";
})(Registers || (exports.Registers = Registers = {}));
